runners:
 AWS-runner:
  image: ubuntu-vitis-2020-1

jobs:   
 build-fast:
  runner: AWS-runner
  type:
   build: software
  input: 
   artifact: 
    - platform/zcu104-firmware
    - bbx/petalinux-sysroot
    - bbx/petalinux-firmware
    - bbx/vitis-libraries
  steps:
   - run:
      name: Download files
      command: |
       git clone https://github.com/mwijeyasinghebbx/test_images
       mv test_images/* /tools/Xilinx/Vitis/2020.1/platforms/xilinx_zcu104_base_202010_1/sw/xilinx_zcu104_base_202010_1/xrt/image/
      type: miscellaneous  
   - run:
      name: Run Software Emulation Build
      command: Emulation-SW/build.sh
      type: sw-emulation      
   
 test-sw-emulation:
  runner: AWS-runner
  depends:
   - build-fast
  type:
   test: sw-emulation
  input: 
   artifact: 
    - build-fast
    - platform/zcu104-firmware
  steps:
   - run:
      name: Run Software Emulation
      command: |
       pwd
       ls
       ./sw_emu.sh 
 
workflows:
 complete-build-test:
  jobs:
   - build-fast
   - test-sw-emulation
